name: Read Secret

on:
  workflow_dispatch:

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  Read-Secret-Of-Github:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::607081650648:role/OidcsRoleForS3
          aws-region: ap-south-1

      - name: Storing Secret in Txt file
        run: |
          echo "${{ secrets.DEMO_SECRET }}" > secret.txt

      - name: Upload to S3
        run: |
          aws s3 cp secret.txt s3://my-oidc-demo-bucket-12345/secrets/secret.txt
          
  
